name: cnn-training
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - notebook
