name: classification_instruments
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - cpuonly
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - tqdm
  - pillow
  - pip
  - pip:
      - librosa
      - soundfile